import React, { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import {
  BarChart3, Download, FileText, Building2, AlertTriangle,
  PlusCircle, RefreshCw,
} from 'lucide-react';
import { apiGet } from '@/lib/api';
import { MONTHS, cn } from '@/lib/utils';

const fmt  = n => '₹' + Number(n || 0).toLocaleString('en-IN', { minimumFractionDigits: 0 });
const fmtN = n => Number(n || 0).toLocaleString('en-IN', { minimumFractionDigits: 2 });

const REPORT_TYPES = [
  { key: 'summary',         label: 'Payroll Summary',    Icon: BarChart3,     endpoint: '/payroll/reports/summary' },
  { key: 'department',      label: 'Department Summary', Icon: Building2,     endpoint: '/payroll/reports/department' },
  { key: 'salary-register', label: 'Salary Register',    Icon: FileText,      endpoint: '/payroll/reports/salary-register' },
  { key: 'lop',             label: 'LOP Report',         Icon: AlertTriangle, endpoint: '/payroll/reports/lop' },
  { key: 'adjustments',     label: 'Adjustments',        Icon: PlusCircle,    endpoint: '/payroll/reports/adjustments' },
];

// ── Column definitions per report type ───────────────────────────────────────
const COLUMNS = {
  summary: [
    { key: 'month',           label: 'Month',       render: (v, r) => `${MONTHS[v - 1]} ${r.year}` },
    { key: 'status',          label: 'Status',      render: v => <StatusPill status={v} /> },
    { key: 'employee_count',  label: 'Employees' },
    { key: 'total_gross',     label: 'Gross',       render: fmt },
    { key: 'total_deductions',label: 'Deductions',  render: fmt },
    { key: 'total_adjustments',label: 'Adjustments',render: fmt },
    { key: 'total_net',       label: 'Net',         render: fmt, bold: true },
    { key: 'generated_by_name',label: 'Generated By' },
  ],
  department: [
    { key: 'department',      label: 'Department',  bold: true },
    { key: 'employee_count',  label: 'Employees' },
    { key: 'total_gross',     label: 'Gross',       render: fmt },
    { key: 'total_deductions',label: 'Deductions',  render: fmt },
    { key: 'total_lop',       label: 'LOP Amount',  render: fmt },
    { key: 'total_lop_days',  label: 'LOP Days' },
    { key: 'total_net',       label: 'Net Salary',  render: fmt, bold: true },
    { key: 'avg_net_salary',  label: 'Avg Net',     render: fmt },
  ],
  'salary-register': [
    { key: 'employee_id',     label: 'Emp ID' },
    { key: 'employee_name',   label: 'Name',        bold: true },
    { key: 'department',      label: 'Department' },
    { key: 'gross_salary',    label: 'Gross',       render: fmt },
    { key: 'lop_days',        label: 'LOP Days' },
    { key: 'lop_amount',      label: 'LOP',         render: fmt },
    { key: 'total_deductions',label: 'Deductions',  render: fmt },
    { key: 'adjustment_total',label: 'Adjustments', render: v => <span className={Number(v) >= 0 ? 'text-emerald-600' : 'text-rose-600'}>{fmt(v)}</span> },
    { key: 'effective_net',   label: 'Net',         render: fmt, bold: true },
    { key: 'present_days',    label: 'Present' },
    { key: 'absent_days',     label: 'Absent' },
  ],
  lop: [
    { key: 'employee_id',     label: 'Emp ID' },
    { key: 'employee_name',   label: 'Name',        bold: true },
    { key: 'department',      label: 'Department' },
    { key: 'working_days',    label: 'Working Days' },
    { key: 'present_days',    label: 'Present' },
    { key: 'absent_days',     label: 'Absent' },
    { key: 'lop_days',        label: 'LOP Days',    bold: true },
    { key: 'lop_amount',      label: 'LOP Amount',  render: fmt, bold: true },
    { key: 'gross_salary',    label: 'Gross',       render: fmt },
    { key: 'net_salary',      label: 'Net',         render: fmt },
  ],
  adjustments: [
    { key: 'adjustment_category', label: 'Category', bold: true },
    { key: 'addition_or_deduction', label: 'Type', render: v => <span className={v === 'addition' ? 'text-emerald-600 font-bold' : 'text-rose-600 font-bold'}>{v}</span> },
    { key: 'count',               label: 'Count' },
    { key: 'total_amount',        label: 'Total Amount', render: fmt, bold: true },
    { key: 'departments',         label: 'Departments' },
  ],
};

function StatusPill({ status }) {
  const MAP = {
    paid: 'bg-emerald-50 text-emerald-700', locked: 'bg-slate-100 text-slate-600',
    approved: 'bg-blue-50 text-blue-700',   verified: 'bg-violet-50 text-violet-700',
    completed: 'bg-teal-50 text-teal-700',  failed: 'bg-red-50 text-red-700',
  };
  return <span className={`text-[0.65rem] font-bold px-2 py-0.5 rounded-full ${MAP[status] || 'bg-gray-100 text-gray-600'}`}>{status}</span>;
}

export default function PayrollReports() {
  const now   = new Date();
  const [type,  setType]  = useState('summary');
  const [month, setMonth] = useState(now.getMonth() + 1);
  const [year,  setYear]  = useState(now.getFullYear());

  const activeReport = REPORT_TYPES.find(r => r.key === type);
  const cols         = COLUMNS[type] || [];

  const { data, isLoading, refetch } = useQuery({
    queryKey: ['payroll-report', type, month, year],
    queryFn:  () => apiGet(activeReport.endpoint, {
      month: month || undefined,
      year:  year  || undefined,
    }),
    enabled: Boolean(activeReport),
  });

  const rows = Array.isArray(data) ? data : [];

  function downloadCsv() {
    const url  = new URL(activeReport.endpoint, window.location.origin);
    const base = `${window.location.origin}/api${activeReport.endpoint}`;
    const params = new URLSearchParams({ format: 'csv' });
    if (month) params.set('month', month);
    if (year)  params.set('year',  year);
    const link = document.createElement('a');
    link.href  = `/api${activeReport.endpoint}?${params}`;
    link.download = `${type}_${month || 'all'}_${year}.csv`;
    link.click();
  }

  return (
    <div className="space-y-5">
      {/* Header */}
      <div className="page-header">
        <div>
          <div className="page-title">Payroll Reports</div>
          <div className="page-subtitle">
            <span className="text-[#777587]">Payroll</span>
            <span className="mx-1.5 text-[#c7c4d8]">›</span>
            Reports
          </div>
        </div>
        <div className="flex items-center gap-2">
          <button onClick={() => refetch()}
            className="flex items-center gap-1.5 px-3 py-2 rounded-lg text-sm font-semibold text-[#464555] border border-[#c7c4d8] bg-white hover:bg-[#f0f3ff] transition-all">
            <RefreshCw size={13} /> Refresh
          </button>
          <button onClick={downloadCsv}
            className="flex items-center gap-1.5 px-4 py-2 rounded-lg text-sm font-bold bg-[#3525cd] text-white hover:bg-[#2a1fb0] transition-all shadow-sm">
            <Download size={14} /> Export CSV
          </button>
        </div>
      </div>

      {/* Report type selector + filters */}
      <div className="bg-white rounded-xl border border-[#e2e0f0] shadow-sm p-4">
        <div className="flex flex-wrap gap-2 mb-4">
          {REPORT_TYPES.map(r => (
            <button key={r.key}
              onClick={() => setType(r.key)}
              className={cn(
                'flex items-center gap-2 px-3 py-2 rounded-lg text-sm font-semibold border transition-all',
                type === r.key
                  ? 'bg-[#3525cd] text-white border-[#3525cd]'
                  : 'bg-white text-[#464555] border-[#c7c4d8] hover:border-[#3525cd]/40 hover:bg-[#f0f3ff]'
              )}>
              <r.Icon size={13} />
              {r.label}
            </button>
          ))}
        </div>

        {/* Period filter */}
        <div className="flex items-center gap-3 pt-3 border-t border-[#f0f3ff]">
          <span className="text-xs font-bold text-[#777587]">Period:</span>
          <select
            value={month}
            onChange={e => setMonth(Number(e.target.value))}
            className="border border-[#c7c4d8] rounded-lg px-2.5 py-1.5 text-sm focus:outline-none focus:border-[#3525cd] bg-white">
            <option value={0}>All months</option>
            {MONTHS.map((m, i) => <option key={i} value={i + 1}>{m}</option>)}
          </select>
          <div className="flex items-center gap-1 bg-white border border-[#c7c4d8] rounded-lg px-2 py-1.5">
            <button onClick={() => setYear(y => y - 1)} className="w-6 h-6 flex items-center justify-center text-[#777587] hover:text-[#3525cd]">‹</button>
            <span className="font-black text-sm text-[#151c27] min-w-[3rem] text-center">{year}</span>
            <button onClick={() => setYear(y => y + 1)} className="w-6 h-6 flex items-center justify-center text-[#777587] hover:text-[#3525cd]">›</button>
          </div>
          <span className="text-xs text-[#777587] ml-auto">{rows.length} row{rows.length !== 1 ? 's' : ''}</span>
        </div>
      </div>

      {/* Data table */}
      <div className="bg-white rounded-xl border border-[#e2e0f0] shadow-sm overflow-hidden">
        {isLoading ? (
          <div className="flex items-center justify-center py-16">
            <div className="w-6 h-6 border-2 border-[#3525cd]/30 border-t-[#3525cd] rounded-full animate-spin" />
          </div>
        ) : rows.length === 0 ? (
          <div className="flex flex-col items-center justify-center py-16 text-center">
            <BarChart3 size={36} className="text-[#c7c4d8] mb-3" />
            <p className="font-semibold text-[#464555]">No data for this period</p>
            <p className="text-sm text-[#777587] mt-1">Try a different month, year, or report type.</p>
          </div>
        ) : (
          <div className="overflow-x-auto">
            <table className="w-full text-sm">
              <thead>
                <tr className="border-b border-[#f0f3ff] bg-[#fafaff]">
                  {cols.map(c => (
                    <th key={c.key} className="text-left px-4 py-3 text-[0.65rem] font-black uppercase tracking-widest text-[#777587] whitespace-nowrap">
                      {c.label}
                    </th>
                  ))}
                </tr>
              </thead>
              <tbody>
                {rows.map((row, i) => (
                  <tr key={i} className={cn('border-b border-[#f9f9ff] hover:bg-[#fafaff] transition-colors', i % 2 === 0 ? 'bg-white' : 'bg-[#fafaff]')}>
                    {cols.map(c => {
                      const val = row[c.key];
                      const displayed = c.render ? c.render(val, row) : (val ?? '—');
                      return (
                        <td key={c.key} className={cn('px-4 py-2.5 whitespace-nowrap', c.bold ? 'font-bold text-[#151c27]' : 'text-[#464555]')}>
                          {displayed}
                        </td>
                      );
                    })}
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </div>
    </div>
  );
}
